/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  /* snip */
}

export interface definitions {
  users: {
    /**
     * Note:
     * This is a Primary Key.<pk/>
     */
    id: string
    username: string
    status: string
    group: number
  }
}

export interface parameters {
  /* snip */
}

export interface operations {
  /* snip */
}
