export { StorageClient } from './StorageClient'
export type { StorageClientOptions } from './StorageClient'
export * from './lib/types'
export * from './lib/errors'
export * from '@supabase/storage-vectors-js'