CREATE TYPE public.address AS (street text, city text);

CREATE TABLE public.inference_cases (
  id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  sequence_id bigint GENERATED BY DEFAULT AS IDENTITY,
  price numeric NOT NULL,
  quantity integer NOT NULL DEFAULT 1,
  total numeric GENERATED ALWAYS AS (price * quantity) STORED,
  note text,
  required_payload jsonb NOT NULL,
  optional_payload jsonb,
  tags text[] NOT NULL DEFAULT '{}',
  scores integer[],
  shipping_address public.address,
  status public.user_status NOT NULL DEFAULT 'ONLINE'
);

CREATE FUNCTION public.inference_case_label(inference_row public.inference_cases)
RETURNS text LANGUAGE sql STABLE AS $$
  SELECT inference_row.note;
$$;

-- A zero-argument function named like a column must not hide that column from select('*').
CREATE FUNCTION public.note()
RETURNS text LANGUAGE sql STABLE AS $$
  SELECT 'note';
$$;

CREATE FUNCTION public.echo_address(address public.address)
RETURNS public.address LANGUAGE sql IMMUTABLE AS $$
  SELECT address;
$$;

CREATE FUNCTION public.sum_scores(scores integer[], offset_by integer DEFAULT 0)
RETURNS integer LANGUAGE sql IMMUTABLE AS $$
  SELECT coalesce(sum(score), 0)::integer + offset_by FROM unnest(scores) AS score;
$$;

-- DISTINCT makes these views not automatically updatable, so only their triggers make them writable.
CREATE VIEW public.trigger_writable_view AS
  SELECT DISTINCT username, status FROM public.users;

CREATE VIEW public.update_only_trigger_view AS
  SELECT DISTINCT username, status FROM public.users;

CREATE FUNCTION public.write_users_through_view()
RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF tg_op = 'INSERT' THEN
    INSERT INTO public.users (username, status) VALUES (new.username, new.status);
  ELSE
    UPDATE public.users SET status = new.status WHERE username = old.username;
  END IF;
  RETURN new;
END;
$$;

CREATE TRIGGER trigger_writable_view_insert
  INSTEAD OF INSERT ON public.trigger_writable_view
  FOR EACH ROW EXECUTE FUNCTION public.write_users_through_view();

CREATE TRIGGER trigger_writable_view_update
  INSTEAD OF UPDATE ON public.trigger_writable_view
  FOR EACH ROW EXECUTE FUNCTION public.write_users_through_view();

CREATE TRIGGER update_only_trigger_view_update
  INSTEAD OF UPDATE ON public.update_only_trigger_view
  FOR EACH ROW EXECUTE FUNCTION public.write_users_through_view();

CREATE MATERIALIZED VIEW public.user_status_counts AS
  SELECT status, count(*)::integer AS total FROM public.users GROUP BY status;

CREATE FUNCTION public.get_user_status_counts()
RETURNS SETOF public.user_status_counts LANGUAGE sql STABLE AS $$
  SELECT * FROM public.user_status_counts;
$$;

CREATE FUNCTION public.describe_status_count(count_row public.user_status_counts)
RETURNS text LANGUAGE sql STABLE AS $$
  SELECT count_row.status::text || ': ' || count_row.total;
$$;

CREATE EXTENSION IF NOT EXISTS postgres_fdw WITH SCHEMA extensions;
CREATE SERVER inference_cases_loopback FOREIGN DATA WRAPPER postgres_fdw OPTIONS (dbname 'postgres');

CREATE FOREIGN TABLE public.remote_users (
  username text NOT NULL,
  status public.user_status
) SERVER inference_cases_loopback OPTIONS (schema_name 'public', table_name 'users');

CREATE FUNCTION public.get_remote_users()
RETURNS SETOF public.remote_users LANGUAGE plpgsql STABLE AS $$
BEGIN
  RETURN QUERY SELECT * FROM public.remote_users;
END;
$$;

CREATE FUNCTION public.describe_remote_user(remote_row public.remote_users)
RETURNS text LANGUAGE sql STABLE AS $$
  SELECT remote_row.username;
$$;

CREATE TABLE personal.user_notes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  author text NOT NULL REFERENCES public.users (username),
  personal_author text REFERENCES personal.users (username),
  note text NOT NULL
);

CREATE FUNCTION personal.username_label(user_row personal.users)
RETURNS text LANGUAGE sql STABLE AS $$
  SELECT upper(user_row.username);
$$;

CREATE FUNCTION public.get_personal_users()
RETURNS SETOF personal.users LANGUAGE sql STABLE AS $$
  SELECT * FROM personal.users;
$$;

GRANT ALL ON ALL TABLES IN SCHEMA personal TO anon, authenticated;
GRANT ALL ON ALL SEQUENCES IN SCHEMA personal TO anon, authenticated;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA personal TO anon, authenticated;
GRANT ALL ON ALL TABLES IN SCHEMA public TO anon, authenticated, service_role;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated, service_role;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO anon, authenticated, service_role;
