name: Test Slack Notification on PR Failure

on:
  push:
    branches:
      - chore/notify-slack-failure

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Dummy step to simulate something that could fail
      - name: Run a test command
        run: exit 1 # This will fail on purpose for the test


  notify-failure:
    needs: test
    if: ${{ always() && needs.test.result == 'failure' }}
    uses: ./.github/workflows/slack-notify.yml
    secrets: inherit
    with:
      subject: "Test CI"