name: SDK Compliance

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  validate:
    uses: supabase/sdk/.github/workflows/validate-sdk-compliance-javascript.yml@main
    with:
      build-command: |
        corepack enable
        pnpm install --frozen-lockfile
        pnpm nx run-many --target=docs:json --output-style=stream
      spec-glob: packages/core/*/docs/v2/spec.json
